name: CI

on: [push]

jobs:
    build_and_run:
        name: Build and run
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
          - uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
            with:
                java-version: '21.0.5+11.0.LTS'
                distribution: 'Temurin'
          - name: Run.sh
            env:
                DEFOLD_USER: bjorn.ritzl@gmail.com
                DEFOLD_AUTH: foobar
            run: ./.test/run.sh
